name: vtech-todo ci
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install node_module
        run: npm ci
      - name: Build into standalone bundle
        run: npm run build

      - name: Build and Push docker-compose for production
        if: github.ref == 'refs/heads/main'
        run: |
          echo '${{secrets.PROD_ENV}}' > .env.production
          docker-compose build production
          docker-compose push production

      - name: Build and Push docker-compose for development
        if: github.ref == 'refs/heads/development'
        run: |
          echo '${{secrets.DEV_ENV}}' > .env.development
          docker-compose build development
          docker-compose push development
