name: vtech-todo ci
on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{secrets.DOCKER_HUB_USERNAME}}
                  password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: Generate env file for development
              if: github.ref == 'refs/heads/development'
              run: echo '${{secrets.DEV_ENV}}' > .env.development

            - name: Generate env file for production
              if: github.ref == 'refs/heads/main'
              run: echo '${{secrets.PROD_ENV}}' > .env.production

            - name: Build and Push docker-compose for production
              if: github.ref == 'refs/heads/main'
              run: |
                  docker-compose build production
                  docker-compose push production

            - name: Build and Push docker-compose for development
              if: github.ref == 'refs/heads/development'
              run: |
                  docker-compose build development
                  docker-compose push development
